CREATE TABLE INDIVIDU (
	NumInd		NUMBER,
	Nom			VARCHAR(60),
	Prenom		VARCHAR(60),
	CONSTRAINT	pk_Ind 	PRIMARY KEY(NumInd)
);

CREATE TABLE FILM (
	NumFilm		NUMBER,
	Titre		VARCHAR(35),
	Realisateur	NUMBER,
	CONSTRAINT	pk_Film			PRIMARY KEY(NumFilm),
	CONSTRAINT 	fk_Film_Real 	FOREIGN KEY(Realisateur) REFERENCES INDIVIDU
);
		
CREATE TABLE ACTEUR (
	NumFilm		NUMBER,
	NumInd		NUMBER,
	CONSTRAINT	pk_Acteur 		PRIMARY KEY(NumFilm, NumInd),
	CONSTRAINT	fk_Acteur_Film 	FOREIGN KEY(NumFilm) 	REFERENCES FILM,
	CONSTRAINT	fk_Acteur_Ind	FOREIGN KEY(NumInd)		REFERENCES INDIVIDU
);

CREATE TABLE GENRE (
	CodeGenre	VARCHAR(2),
	Libelle		VARCHAR(30),
	CONSTRAINT	pk_Genre	PRIMARY KEY(CodeGenre)
);

CREATE TABLE FILM_GENRE (
	NumFilm		NUMBER,
	CodeGenre	VARCHAR(2),
	CONSTRAINT	pk_fg		PRIMARY KEY(NumFilm, CodeGenre),
	CONSTRAINT	fk_fg_Film	FOREIGN KEY(NumFilm) 	REFERENCES FILM,
	CONSTRAINT	fk_fg_Genre	FOREIGN KEY(CodeGenre)	REFERENCES GENRE
);