INSERT	INTO	INDIVIDU	VALUES	(1, 'Spielberg', 'Steven');
INSERT	INTO	INDIVIDU	VALUES	(2, 'Cruise', 'Tom');
INSERT	INTO	INDIVIDU	VALUES 	(3, 'Farell', 'Colin' );
INSERT	INTO	INDIVIDU	VALUES	(4, 'John', 'Travolta');
INSERT	INTO	INDIVIDU	VALUES	(5, 'Samuel L.', 'Jackson');
INSERT	INTO	INDIVIDU	VALUES 	(6, 'Tarentino', 'Quantin');
INSERT	INTO	INDIVIDU	VALUES	(7, 'Hanks', 'Tom');
INSERT	INTO	INDIVIDU	VALUES	(8, 'Foxx', 'Jamie');
INSERT	INTO	INDIVIDU	VALUES	(9, 'Zemeckics', 'Robert');
INSERT	INTO	INDIVIDU	VALUES	(10, 'Eastwood', 'Clint');
INSERT	INTO	INDIVIDU	VALUES	(11, 'Roberts', 'Julia');
INSERT	INTO	INDIVIDU	VALUES	(12, 'Bale', 'Christian');
INSERT	INTO	INDIVIDU	VALUES	(13, 'Neeson', 'Liam');

INSERT	INTO	FILM		VALUES	(1, 'Forest Gomp', 9);
INSERT	INTO	FILM		VALUES	(2, 'Schindlers List', 1);
INSERT	INTO	FILM		VALUES	(3, 'Minority Report', 1);
INSERT	INTO	FILM		VALUES	(4, 'Pulp Fiction', 6);
INSERT	INTO	FILM		VALUES	(5, 'Djaingo Unchained', 6);
INSERT	INTO	FILM		VALUES	(6, 'Gran Torino', 10);

INSERT	INTO	ACTEUR		VALUES	(1, 7);
INSERT	INTO	ACTEUR		VALUES	(2, 13);
INSERT	INTO	ACTEUR		VALUES	(3, 2);
INSERT	INTO	ACTEUR		VALUES	(4, 4);
INSERT	INTO	ACTEUR		VALUES	(4, 5);
INSERT	INTO	ACTEUR		VALUES	(5, 8);
INSERT	INTO	ACTEUR		VALUES	(5, 6);
INSERT	INTO	ACTEUR		VALUES	(6, 10);

INSERT	INTO	GENRE		VALUES	('D', 'Drame');
INSERT	INTO	GENRE		VALUES	('C', 'Comedie');
INSERT	INTO	GENRE		VALUES	('P', 'Policier');
INSERT	INTO	GENRE		VALUES	('SF', 'Science Fiction');
INSERT	INTO	GENRE		VALUES	('H', 'Histoire');

INSERT	INTO	FILM_GENRE	VALUES	(1, 'D');
INSERT	INTO	FILM_GENRE	VALUES	(1, 'C');
INSERT	INTO	FILM_GENRE	VALUES	(2, 'H');
INSERT	INTO	FILM_GENRE	VALUES	(3, 'SF');
INSERT	INTO	FILM_GENRE	VALUES	(4, 'P');
INSERT	INTO	FILM_GENRE	VALUES	(4, 'C');
INSERT	INTO	FILM_GENRE	VALUES	(5, 'H');
INSERT	INTO	FILM_GENRE	VALUES	(6, 'P');